name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup SSH Key
      run: |
        mkdir -p ~/.ssh
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Test SSH Connection
      run: |
        ssh -o StrictHostKeyChecking=no root@103.127.29.215 "echo 'SSH connection successful'"

    - name: Install pm2
      run: sudo npm install pm2 -g

    - name: Move project to new directory
      run: |
        sudo mv /root/fota-backend /home/ubuntu/fota-backend
        sudo chown -R ubuntu:ubuntu /home/ubuntu/fota-backend
      env:
        USER: ubuntu

    - name: Install dependencies
      run: |
        cd /home/ubuntu/fota-backend
        npm install

    - name: Restart app with pm2
      run: |
        cd /home/ubuntu/fota-backend
        pm2 stop fota-backend || true  # Stop if running
        pm2 delete fota-backend || true # Remove from pm2's process list
        pm2 start index.js --name fota-backend
